// examples/vue/src/App.vue
<template>
  <div class="app">
    <header>
      <h1>🚀 Code Editor - Vue 3 Example</h1>
    </header>

    <div class="controls">
      <select v-model="language" class="control-select">
        <option value="javascript">JavaScript</option>
        <option value="typescript">TypeScript</option>
        <option value="python">Python</option>
        <option value="java">Java</option>
        <option value="cpp">C++</option>
        <option value="go">Go</option>
        <option value="rust">Rust</option>
        <option value="html">HTML</option>
        <option value="css">CSS</option>
        <option value="json">JSON</option>
        <option value="markdown">Markdown</option>
      </select>

      <select v-model="theme" class="control-select">
        <option value="vs-dark">VS Dark</option>
        <option value="vs">VS Light</option>
        <option value="hc-black">High Contrast</option>
      </select>

      <input v-model.number="fontSize" type="number" min="10" max="30" class="control-input" placeholder="Font Size">

      <button @click="handleFormat" class="control-btn">格式化代码</button>
      <button @click="handleGetValue" class="control-btn">获取内容</button>
      <button @click="handleClear" class="control-btn">清空</button>
      <button @click="handleUndo" class="control-btn">撤销</button>
      <button @click="handleRedo" class="control-btn">重做</button>
      <button @click="toggleReadOnly" class="control-btn">{{ readOnly ? '取消只读' : '切换只读' }}</button>
    </div>

    <div class="editor-wrapper">
      <CodeEditor
        ref="editorRef"
        v-model="code"
        :language="language"
        :theme="theme"
        :font-size="fontSize"
        :read-only="readOnly"
        :minimap="true"
        :folding="true"
        :line-numbers="'on'"
        :auto-complete="true"
        @ready="onEditorReady"
        @change="onCodeChange"
        @cursor-change="onCursorChange"
        @focus="onFocus"
        @blur="onBlur"
      />
    </div>

    <div class="stats">
      <div><strong>状态:</strong> {{ status }}</div>
      <div><strong>行数:</strong> {{ lineCount }}</div>
      <div><strong>光标位置:</strong> {{ cursorPos }}</div>
      <div><strong>选中文本:</strong> {{ selectedText }}</div>
      <div><strong>代码长度:</strong> {{ code.length }} 字符</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { CodeEditor } from '@ldesign/code-editor-vue'
import type { CodeEditor as CoreCodeEditor } from '@ldesign/code-editor-core'
import type * as Monaco from 'monaco-editor'

const initialCode = `// 欢迎使用 LDesign Code Editor Vue 3 组件!
// 这是一个功能强大的代码编辑器

<template>
  <div class="hello-world">
    <h1>{{ message }}</h1>
    <button @click="count++">点击次数: {{ count }}</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const message = ref('Hello Vue 3!')
const count = ref(0)
<\/script>

// 支持的特性:
// ✓ 双向绑定 (v-model)
// ✓ 响应式更新
// ✓ 语法高亮
// ✓ 自动补全
// ✓ 代码格式化
// ✓ 多语言支持
// ✓ 主题切换
`

const editorRef = ref<InstanceType<typeof CodeEditor>>()
const code = ref(initialCode)
const language = ref('javascript')
const theme = ref('vs-dark')
const fontSize = ref(14)
const readOnly = ref(false)
const status = ref('初始化中...')
const lineCount = ref(0)
const cursorPos = ref('1:1')
const selectedText = ref('无')

const onEditorReady = (editor: CoreCodeEditor) => {
  status.value = '就绪'
  updateStats()
  console.log('Editor ready!', editor)
}

const onCodeChange = (value: string) => {
  updateStats()
  console.log('Code changed:', value.length, 'characters')
}

const onCursorChange = (position: Monaco.Position) => {
  cursorPos.value = `${position.lineNumber}:${position.column}`
}

const onFocus = () => {
  status.value = '已聚焦'
}

const onBlur = () => {
  status.value = '失去焦点'
}

const updateStats = () => {
  if (!editorRef.value) return

  const editor = editorRef.value.editor
  if (!editor) return

  const state = editor.getState()
  lineCount.value = state.lineCount

  const selection = editor.getSelection()
  selectedText.value = selection ? `已选中 ${selection.length} 个字符` : '无'
}

const handleFormat = async () => {
  await editorRef.value?.format()
  status.value = '代码已格式化'
}

const handleGetValue = () => {
  const value = editorRef.value?.getValue()
  console.log('Editor content:', value)
  alert(`内容长度: ${value?.length} 个字符\n(详细内容请查看控制台)`)
}

const handleClear = () => {
  if (confirm('确定要清空编辑器内容吗?')) {
    code.value = ''
    status.value = '已清空'
  }
}

const handleUndo = () => {
  editorRef.value?.undo()
  status.value = '已撤销'
}

const handleRedo = () => {
  editorRef.value?.redo()
  status.value = '已重做'
}

const toggleReadOnly = () => {
  readOnly.value = !readOnly.value
  status.value = readOnly.value ? '只读模式' : '编辑模式'
}
</script>

<style scoped>
.app {
  max-width: 1400px;
  margin: 0 auto;
  padding: 20px;
}

header {
  margin-bottom: 20px;
}

h1 {
  color: #667eea;
  font-size: 32px;
  margin: 0;
}

.controls {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
  flex-wrap: wrap;
}

.control-select,
.control-input {
  padding: 10px;
  background: #2d2d30;
  color: white;
  border: 1px solid #3e3e42;
  border-radius: 4px;
  font-size: 14px;
}

.control-input {
  width: 80px;
}

.control-btn {
  padding: 10px 20px;
  background: #667eea;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background 0.3s;
}

.control-btn:hover {
  background: #5568d3;
}

.control-btn:active {
  background: #4451b8;
}

.editor-wrapper {
  width: 100%;
  height: 600px;
  border: 1px solid #3e3e42;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
}

.stats {
  margin-top: 20px;
  padding: 15px;
  background: #2d2d30;
  border-radius: 8px;
  font-family: 'Courier New', monospace;
  font-size: 14px;
}

.stats div {
  margin-bottom: 5px;
}

.stats strong {
  color: #667eea;
}
</style>

// examples/react/src/App.tsx
import React, { useState, useRef } from 'react'
import { CodeEditor, type CodeEditorRef } from '@ldesign/code-editor-react'
import type { CodeEditor as CoreCodeEditor } from '@ldesign/code-editor-core'
import type * as Monaco from 'monaco-editor'

const initialCode = `// 欢迎使用 LDesign Code Editor React 组件!
// 这是一个功能强大的代码编辑器

import React, { useState } from 'react'

function Counter() {
  const [count, setCount] = useState(0)

  return (
    <div className="counter">
      <h1>Hello React!</h1>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  )
}

export default Counter

// 支持的特性:
// ✓ 受控/非受控组件
// ✓ Hooks 支持
// ✓ 语法高亮
// ✓ 自动补全
// ✓ 代码格式化
// ✓ 多语言支持
// ✓ 主题切换
// ✓ TypeScript 完整类型支持
`

function App() {
  const editorRef = useRef<CodeEditorRef>(null)
  const [code, setCode] = useState(initialCode)
  const [language, setLanguage] = useState('javascript')
  const [theme, setTheme] = useState('vs-dark')
  const [fontSize, setFontSize] = useState(14)
  const [readOnly, setReadOnly] = useState(false)
  const [status, setStatus] = useState('初始化中...')
  const [lineCount, setLineCount] = useState(0)
  const [cursorPos, setCursorPos] = useState('1:1')
  const [selectedText, setSelectedText] = useState('无')

  const onEditorReady = (editor: CoreCodeEditor) => {
    setStatus('就绪')
    updateStats()
    console.log('Editor ready!', editor)
  }

  const onCodeChange = (value: string) => {
    setCode(value)
    updateStats()
    console.log('Code changed:', value.length, 'characters')
  }

  const onCursorChange = (position: Monaco.Position) => {
    setCursorPos(`${position.lineNumber}:${position.column}`)
  }

  const onFocus = () => {
    setStatus('已聚焦')
  }

  const onBlur = () => {
    setStatus('失去焦点')
  }

  const updateStats = () => {
    if (!editorRef.current) return

    const editor = editorRef.current.editor
    if (!editor) return

    const state = editor.getState()
    setLineCount(state.lineCount)

    const selection = editor.getSelection()
    setSelectedText(selection ? `已选中 ${selection.length} 个字符` : '无')
  }

  const handleFormat = async () => {
    await editorRef.current?.format()
    setStatus('代码已格式化')
  }

  const handleGetValue = () => {
    const value = editorRef.current?.getValue()
    console.log('Editor content:', value)
    alert(`内容长度: ${value?.length} 个字符\n(详细内容请查看控制台)`)
  }

  const handleClear = () => {
    if (confirm('确定要清空编辑器内容吗?')) {
      setCode('')
      setStatus('已清空')
    }
  }

  const handleUndo = () => {
    editorRef.current?.undo()
    setStatus('已撤销')
  }

  const handleRedo = () => {
    editorRef.current?.redo()
    setStatus('已重做')
  }

  const toggleReadOnly = () => {
    setReadOnly(!readOnly)
    setStatus(!readOnly ? '只读模式' : '编辑模式')
  }

  return (
    <div className="app">
      <header>
        <h1>🚀 Code Editor - React Example</h1>
      </header>

      <div className="controls">
        <select value={language} onChange={(e) => setLanguage(e.target.value)} className="control-select">
          <option value="javascript">JavaScript</option>
          <option value="typescript">TypeScript</option>
          <option value="python">Python</option>
          <option value="java">Java</option>
          <option value="cpp">C++</option>
          <option value="go">Go</option>
          <option value="rust">Rust</option>
          <option value="html">HTML</option>
          <option value="css">CSS</option>
          <option value="json">JSON</option>
          <option value="markdown">Markdown</option>
        </select>

        <select value={theme} onChange={(e) => setTheme(e.target.value)} className="control-select">
          <option value="vs-dark">VS Dark</option>
          <option value="vs">VS Light</option>
          <option value="hc-black">High Contrast</option>
        </select>

        <input
          type="number"
          value={fontSize}
          onChange={(e) => setFontSize(Number(e.target.value))}
          min="10"
          max="30"
          className="control-input"
          placeholder="Font Size"
        />

        <button onClick={handleFormat} className="control-btn">格式化代码</button>
        <button onClick={handleGetValue} className="control-btn">获取内容</button>
        <button onClick={handleClear} className="control-btn">清空</button>
        <button onClick={handleUndo} className="control-btn">撤销</button>
        <button onClick={handleRedo} className="control-btn">重做</button>
        <button onClick={toggleReadOnly} className="control-btn">
          {readOnly ? '取消只读' : '切换只读'}
        </button>
      </div>

      <div className="editor-wrapper">
        <CodeEditor
          ref={editorRef}
          value={code}
          language={language}
          theme={theme}
          fontSize={fontSize}
          readOnly={readOnly}
          minimap={true}
          folding={true}
          lineNumbers="on"
          autoComplete={true}
          onChange={onCodeChange}
          onReady={onEditorReady}
          onCursorChange={onCursorChange}
          onFocus={onFocus}
          onBlur={onBlur}
        />
      </div>

      <div className="stats">
        <div><strong>状态:</strong> {status}</div>
        <div><strong>行数:</strong> {lineCount}</div>
        <div><strong>光标位置:</strong> {cursorPos}</div>
        <div><strong>选中文本:</strong> {selectedText}</div>
        <div><strong>代码长度:</strong> {code.length} 字符</div>
      </div>
    </div>
  )
}

export default App
